#!/bin/sh

[ "$(uci get system.@system[-1].linkit_firstboot)" = "1" ] && return 0

. /lib/ramips.sh
board=$(ramips_board_name)

[ "$board" = "linkits7688d" ] || rm /etc/avahi/services/arduino.service

. /lib/functions.sh

uci set system.@system[-1].hostname="myLinkIt"
uci set wireless.radio0.disabled=0
uci set network.lan.ipaddr=192.168.100.1

SSID=`fw_printenv -n wifi_ssid`
KEY=`fw_printenv -n wifi_key`
SEQ=`fw_printenv -n wifi_seq`
[ -n "${SSID}" ] || \
	SSID=LinkIt_Smart_7688
[ -n "${SEQ}" ] || \
	SEQ=1
uci set wireless.ap.ssid="$SSID"
uci set wireless.ap.seq="$SEQ"

[ -n "${KEY}" ] && {
	uci set wireless.ap.encryption='psk2'
	uci set wireless.ap.key="$KEY"
}

uci set network.wan=interface
uci set network.wan.proto=dhcp

uci set mountd.mountd.path=/Media/

uci add_list uhttpd.main.alias='/arduino/=/cgi-bin/luci/'
uci add_list uhttpd.main.alias='/data/=/cgi-bin/luci/'
uci add_list uhttpd.main.alias='/mailbox/=/cgi-bin/luci/'

uci commit
return 0
